
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bruh123
      POSTGRES_DB: postgres
    networks:
      - my_network
    ports:
      - "5432:5432"
    restart: always

  user-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.userapp
    environment:
      DATABASE_URL: postgresql://postgres:bruh123@db:5432/postgres
      WEBHOOK_URL: http://webhook-handler:3003
    depends_on:
      - db
    networks:
      - my_network
    ports:
      - "3001:3001"
    develop:
      watch:
      - path: package*.json
        action: rebuild
      - path: ./app/user-app/package*.json
        action: rebuild
      - path: ./app/user-app/
        target: /usr/src/app
        action: sync 

  webhook-handler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.webhook
    environment:
      DATABASE_URL: postgresql://postgres:bruh123@db:5432/postgres
      PORT: 3003
    depends_on:
      - db
    networks:
      - my_network
    ports:
      - "3003:3003"

networks:
  my_network:
    driver: bridge