# Use the official PostgreSQL image from the Docker Hub
FROM postgres:alpine

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=bruh123
ENV POSTGRES_DB=postgres

# Expose the PostgreSQL port
EXPOSE 5432