FROM node:20.12.0-alpine3.19
WORKDIR /usr/src/app
COPY ../package*.json ../turbo.json ../tsconfig.json ./
COPY ../apps/bank-webhook-handler ./apps/bank-webhook-handler
COPY ../packages ./packages
RUN npm install
RUN npm run db:generate
WORKDIR /usr/src/app/apps/bank-webhook-handler
EXPOSE 3003
CMD ["npm", "run", "dev"]