name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push User App Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.userapp
          push: true
          tags: dhanush2313/user-app:latest

      - name: Build and Push Webhook Handler Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.webhook
          push: true
          tags: dhanush2313/webhook-handler:latest

      - name: Push Docker Compose File
        run: |
          docker-compose -f docker-compose.yml push

      - name: Verify Pushed User App Image
        run: docker pull dhanush2313/user-app:latest

      - name: Verify Pushed Webhook Handler Image
        run: docker pull dhanush2313/webhook-handler:latest
